### ISSUE TITLE
Nommer une personne plus jeune et en bonne santé et lui demander de faire les courses pendant toute la période du confinement.

### ISSUE THREAD

**Issue by hack242** [AfricaDevs/APP-SANTE-AFRIQUE-VS-COVID19-TOA#22]
Nommer une personne plus jeune et en bonne santé et lui demander de faire les courses pendant toute la période du confinement.
![2_linkedin](https://user-images.githubusercontent.com/66922483/84630271-9e9b2b80-aee3-11ea-966b-b527d930077b.png)

**Comment by steve111MV** [comment]
fixed
